// Builds the offline web version into the `dist` folder.
// Upload that folder to a free host, open it once on the iPhone in Safari,
// then Share → Add to Home Screen. After that it works with no signal.
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const dist = 'dist';

execSync('npx expo export --platform web', { stdio: 'inherit' });

// Home screen icon + app info, and the privacy policy page the app stores link to
fs.copyFileSync('assets/icon.png', path.join(dist, 'app-icon.png'));
fs.copyFileSync('store/privacy.html', path.join(dist, 'privacy.html'));
fs.writeFileSync(
  path.join(dist, 'manifest.json'),
  JSON.stringify(
    {
      name: 'Construction Calc',
      short_name: 'Constr Calc',
      start_url: '/',
      scope: '/',
      display: 'standalone',
      orientation: 'portrait',
      background_color: '#FFFFFF',
      theme_color: '#FFB300',
      icons: [{ src: '/app-icon.png', sizes: '1024x1024', type: 'image/png', purpose: 'any' }],
    },
    null,
    2,
  ),
);

// Every file in the build gets saved on the phone for offline use.
function listFiles(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? listFiles(full) : [full];
  });
}
const files = listFiles(dist)
  .map((f) => '/' + path.relative(dist, f).split(path.sep).join('/'))
  .filter((f) => f !== '/sw.js');

const version = Date.now();
fs.writeFileSync(
  path.join(dist, 'sw.js'),
  `// Offline cache (generated by scripts/build-web.mjs)
const CACHE = 'construction-calc-${version}';
const FILES = ${JSON.stringify(['/', ...files], null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const isPage = event.request.mode === 'navigate';
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(event.request).catch(() =>
          // Offline: pages fall back to the app; anything else (e.g. host-injected scripts) just fails quietly.
          isPage ? caches.match('/index.html') : new Response('', { status: 504 }),
        ),
    ),
  );
});
`,
);

// Add home-screen tags and turn on the offline cache.
const indexPath = path.join(dist, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replace(
  /<meta name="viewport"[^>]*>/,
  '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
);
html = html.replace(
  '</head>',
  `<link rel="manifest" href="/manifest.json">
<link rel="apple-touch-icon" href="/app-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Constr Calc">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<style>* { touch-action: manipulation; -webkit-tap-highlight-color: transparent; }</style>
</head>`,
);
html = html.replace(
  '</body>',
  `<script>if ('serviceWorker' in navigator) { window.addEventListener('load', function () { navigator.serviceWorker.register('/sw.js'); }); }</script>
</body>`,
);
fs.writeFileSync(indexPath, html);

console.log(`\nOffline web app ready in the "${dist}" folder (${files.length} files).`);
